%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. JPEG_QUALITY=40, SVGA, XCLK=20MHz
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 851.428915
Camera.fy: 851.594450 
Camera.cx: 392.747672
Camera.cy: 296.249843

Camera.k1: 0.366463
Camera.k2: -1.146062
Camera.p1: -0.006593
Camera.p2: -0.004426

# Camera frames per second 
Camera.fps: 10

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0

# Camera resolution 800x600
Camera.width: 800
Camera.height: 600

# Transformation from body-frame (imu) to camera
Tbc: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f

  data: [-0.0477393, -0.99879821, -0.01109437, 0.00076445, 
         -0.72820853, 0.02719926, 0.6848157, 0.00053641,
         -0.68369094, 0.04077164, -0.72863185, 0.00008653,
         0.0, 0.0, 0.0, 1.0]

# IMU noise parameters
IMU.NoiseGyro: 0.0002907488196208217
IMU.NoiseAcc: 0.006610373541864706
IMU.GyroWalk: 0.00010133331044509858
IMU.AccWalk: 0.0008249390143765661
IMU.Frequency: 100

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500
Viewer.imageViewScale: 1


